# # Defines a default set of lint rules enforced for
# # projects at Google. For details and rationale,
# # see https://github.com/dart-lang/pedantic#enabled-lints.
# # include: package:pedantic/analysis_options.yaml

# # For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# # Uncomment to specify additional rules.
linter:
  rules:
    # - avoid_as
    - camel_case_types
    - avoid_print
    - unnecessary_new
    - empty_statements
    - hash_and_equals
    - no_duplicate_case_values
    - prefer_void_to_null
    - prefer_single_quotes
    - always_declare_return_types
    # - always_specify_types
    - avoid_init_to_null
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_unused_constructor_parameters
    - cascade_invocations
    - directives_ordering
    - empty_constructor_bodies
    - file_names
    - flutter_style_todos
    - implementation_imports
    - non_constant_identifier_names
    - null_closures
    - only_throw_errors
    - prefer_is_empty
    - prefer_if_null_operators
    - prefer_null_aware_operators
analyzer:
  errors:
    # avoid_as: error
    camel_case_types: error
    avoid_print: error
    unnecessary_new: error
    no_duplicate_case_values: error
    prefer_void_to_null: error
    avoid_init_to_null: error
    avoid_returning_null_for_void: error
    empty_constructor_bodies: error
    file_names: error
    null_closures: error
    invalid_use_of_protected_member: error