CREATE TABLE `AUTHENTICATION`(
    `Username`      VARCHAR(32) PRIMARY KEY,
    `Token`         VARCHAR(100),
    `TimeOut`       DATETIME,
    FOREIGN KEY (`Username`) REFERENCES ACCOUNT(Username),
)

CREATE TABLE `ACCOUNTTYPE`(
    `ID`            INT AUTO_INCREMENT PRIMARY KEY,
    `Name`          VARCHAR(100)
);

CREATE TABLE `ACCOUNT` (
    `Username`      VARCHAR(32) PRIMARY KEY,
    `Password`      VARCHAR(128) NOT NULL,
    `DisplayName`   VARCHAR(100),
    `Sex`           INT(1),
    `IDCard`        VARCHAR(30),
    `Address`       VARCHAR(100),
    `PhoneNumber`   VARCHAR(30),
    `BirthDay`      DATETIME,
    `IDAccountType` INT,
    `IDImage`       INT,
    FOREIGN KEY(`IDAccountType`) REFERENCES ACCOUNTTYPE(ID),
    FOREIGN KEY(`IDImage`) REFERENCES image(ID)
);

CREATE TABLE `IMAGE`(
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `Data` LONGBLOD
)

CREATE TABLE `TABLE` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(100) DEFAULT 'No Name',
    `Status` INT DEFAULT -1
);

CREATE TABLE `FOODCATEGORY`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(100) DEFAULT 'No Name'
);

CREATE TABLE `FOOD`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `IDCategory` INT NOT NULL,
    `Name` VARCHAR(100) DEFAULT 'No Name',
    `Price` DOUBLE DEFAULT 0,
    FOREIGN KEY(ID) REFERENCES FOODCATEGORY(ID)
);

CREATE TABLE `BILL`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `IDTable` INT NOImageT NULL ,
    `DateCheckIn` DAImageTETIME,
    `DateCheckOut` DImageATETIME,
    `Discount` DOUBLImageE DEFAULT 0,
    `TotalPrice` DOUImageBLE DEFAULT 0,
    `Status` INT DEFImageAULT -1,
    FOREIGN KEY(IDTaImageble) REFERENCES `TABLE`(ID)
);Image
Image
CREATE TABLE `BILLINImageFO`(
    `IDBill` INT NOTImage NULL ,
    `IDFood` INT NOTImage NULL ,
    `Quantity` INT DImageEFAULT 0,
    FOREIGN KEY(IDBill) REFERENCES BILL(ID),
    FOREIGN KEY(IDFood) REFERENCES FOOD(ID)
);




CREATE TABLE `PENDING`(
    `IDBill` INT
);

CREATE TABLE `BIN`(
    `IDCollection` INT,
    `IDElement` INT
)


CREATE TABLE `REPORT`(
    `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Date` Date,
    `TotalPrice` DOUBLE DEFAULT 0
);